name: AI Prediction Deployment
on:
  push:
    branches: [ main, master ]
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy AI prediction service
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_IP }}
          username: ${{ secrets.SSH_ID }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd ~/docker
            
            # 서비스 빌드 및 재시작
            docker-compose build ai-prediction
            docker-compose up -d ai-prediction
            
            # 배포 확인
            docker-compose ps ai-prediction
            docker-compose logs --tail=50 ai-prediction