name: AI Prediction Deployment
on:
  push:
    branches: [ main, master ]
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy AI prediction service
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_IP }}
          username: ${{ secrets.SSH_ID }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            # 올바른 Git 저장소 경로로 이동
            cd ~/ai-prediction
            git pull origin main
            
            # Docker 디렉토리로 이동하여 ai-prediction 서비스만 재시작
            cd ~/docker
            docker-compose stop ai-prediction
            docker-compose rm -f ai-prediction
            docker-compose up -d ai-prediction
            
            # 배포 확인
            docker-compose ps ai-prediction
            docker-compose logs --tail=20 ai-prediction