name: AI Prediction Deployment

on:
  push:
    branches: [ main, master ]
    paths:
      - 'ai-prediction/**'
      - '.github/workflows/deploy.yml'
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          
      - name: Install dependencies
        run: |
          cd ai-prediction
          python -m pip install --upgrade pip
          pip install pytest
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          
      - name: Run tests
        run: |
          cd ai-prediction
          if [ -d tests ]; then
            pytest tests/ -v
          else
            echo "No tests directory found, skipping tests"
          fi

  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Deploy to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_IP }}
          username: ${{ secrets.SSH_ID }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd ~/aiot2-team3
            git pull origin main
            cd docker
            # ai-prediction 서비스만 다시 빌드하고 시작
            docker-compose up -d --build ai-prediction
            
      - name: Verify deployment
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_IP }}
          username: ${{ secrets.SSH_ID }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd ~/aiot2-team3/docker
            docker-compose ps ai-prediction
            docker-compose logs --tail=50 ai-prediction