name: AI Prediction Deployment

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          
      - name: Check directory structure
        run: |
          ls -la
          # ai-prediction 디렉토리가 있는지 확인
          if [ -d "ai-prediction" ]; then
            echo "ai-prediction directory exists"
          else
            echo "ai-prediction directory does not exist, checking parent directory"
            ls -la ..
          fi
          
      - name: Install dependencies
        run: |
          # 디렉토리가 존재하면 진행
          if [ -d "ai-prediction" ]; then
            cd ai-prediction
            python -m pip install --upgrade pip
            pip install pytest
            if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          else
            echo "Skipping dependency installation as ai-prediction directory doesn't exist"
          fi
          
      - name: Run tests
        run: |
          if [ -d "ai-prediction" ] && [ -d "ai-prediction/tests" ]; then
            cd ai-prediction
            pytest tests/ -v
          else
            echo "No ai-prediction/tests directory found, skipping tests"
          fi

  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Deploy to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_IP }}
          username: ${{ secrets.SSH_ID }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd ~/aiot2-team3
            git pull origin main
            # ai-prediction 디렉토리가 있는지 확인 후 처리
            if [ -d "ai-prediction" ]; then
              echo "Deploying AI Prediction service"
              cd docker
              # ai-prediction 서비스만 다시 빌드하고 시작
              docker-compose up -d --build ai-prediction
            else
              echo "ai-prediction directory not found, skipping deployment"
            fi
            
      - name: Verify deployment
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_IP }}
          username: ${{ secrets.SSH_ID }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd ~/aiot2-team3/docker
            docker-compose ps | grep ai-prediction || echo "ai-prediction service not running"
            docker-compose logs --tail=50 ai-prediction || echo "Could not fetch logs"