name: AI Prediction Deployment
on:
  push:
    branches: [ main, master ]
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Copy files to server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SSH_IP }}
          username: ${{ secrets.SSH_ID }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          source: "ai-prediction/"
          target: "~"
          
      - name: Update docker-compose and deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_IP }}
          username: ${{ secrets.SSH_ID }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd ~/docker
            
            # docker-compose.yml에 ai-prediction 서비스 추가
            if ! grep -q "ai-prediction:" docker-compose.yml; then
              echo "Adding ai-prediction service to docker-compose.yml"
              cp docker-compose.yml docker-compose.yml.bak
              
              # 단일 파일로 저장
              echo "  ai-prediction:
    build: 
      context: ../ai-prediction
      dockerfile: Dockerfile
    container_name: javame-ai-prediction
    environment:
      - INFLUXDB_URL=http://influxdb:8086
      - INFLUXDB_TOKEN=g-W7W0j9AE4coriQfnhHGMDnDhTZGok8bgY1NnZ6Z0EnTOsFY3SWAqDTC5fYlQ9mYnbK_doR074-a4Dgck2AOQ==
      - INFLUXDB_ORG=javame
      - INFLUXDB_BUCKET=aiot
      - PREDICTION_INTERVAL=6
    volumes:
      - ../ai-prediction:/app
    networks:
      - javame-network
    restart: unless-stopped
    depends_on:
      - influxdb" > ai-prediction-service.txt
              
              # volumes: 라인 앞에 삽입
              sed -i '/^volumes:/i\\' docker-compose.yml
              sed -i '/^volumes:/e cat ai-prediction-service.txt' docker-compose.yml
              rm ai-prediction-service.txt
            else
              echo "ai-prediction service already exists in docker-compose.yml"
            fi
            
            # 서비스 빌드 및 시작
            docker-compose build ai-prediction
            docker-compose up -d ai-prediction
            
            # 배포 확인
            docker-compose ps | grep ai-prediction || echo "ai-prediction service not running"
            docker-compose logs --tail=20 ai-prediction