name: AI Prediction Deployment
on:
  push:
    branches: [ main, master ]
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy AI prediction service
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_IP }}
          username: ${{ secrets.SSH_ID }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd ~/ai-prediction
            git pull origin main
            cd ~/docker
            docker-compose stop ai-prediction
            docker-compose rm -f ai-prediction
            docker-compose up -d ai-prediction